title: Marselinus Alberto
logo: sources/img/headshot_circle.png
description: Data Science Project Portfolio
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
